import random
print("Welcome to the US Coin Changer Site!")
print("This is a wonderful opportunity to test your basic mathematics skills and to learn how to make change in real life.")
print("This is a great game for children and a wonderful manner to train employees who may be working with cash.")
print("This is such a lost art in our culture these days! Let's do what we can to change it!!")
user_name = input("What is your name, by the way, before we get started? I did not mean to be so rude, Sincerely apologize, let's get started!......")
print(f"Hello {user_name}, it is my pleasure to meet you!")
coin_number = int(input("How many total coins of various types do you have in your possession? (ex. 24)........."))
coin_types = int(input("How many different coin types do you have in your possession? (ex. 3)............"))
coin_type1 = int(input("What is the value of the first coin that you have in your collection? (no decimals, ex. 25)........"))
type1_number = int(input("How many of the first coin that you have in your collection? (ex. 25)........"))
coin_type2 = int(input("What is the value of the second coin that you have in your collection? (no decimals, ex. 25)........"))
type2_number = int(input("How many of the second coin that you have in your collection? (ex. 25)........"))
coin_type3 = int(input("What is the value of the third coin that you have in your collection? (no decimals, ex. 25)........"))
type3_number = int(input("How many of the third coin that you have in your collection? (ex. 25)........"))
coin_type4 = int(input("What is the value of the fourth coin that you have in your collection? (no decimals, ex. 25)........"))
type4_number = int(input("How many of the fourth coin that you have in your collection? (ex. 25)........"))
print("Thank you, now we will begin to conduct our analysis on the total valuation of the coins")
coin_valuation = (coin_type1 * type1_number + coin_type2 * type2_number + coin_type2 * type3_number + coin_type4 * type4_number)
print (coin_valuation)
print(f"Thank you, it was great working with you, {user_name}! You have an amazing collection. Your collection is valued at a total of ${coin_valuation}. I believe that it is worth more at an auction, however today, I can only offer you ${coin_valuation * .5} for your collection. As you know I have to make a profit on the resale. Thanks again for allowing us to assess your collection. I think that you will find this deal to be a fair and equitable offer. Please let me know what you think! Have a great day and I am excited to complete this transaction.")
